 const EduDetailTestData = 
//  [{
//     rId : 1,
//     uId : "서동주",
//     eId : 1,
//     title : "어렵지만 강사진과 내용 모두 훌륭한 교육",
//     content : "비전공자였던 제 입장에서는 매우 생소하고 어려운 기술들이었지만 친절한 강사님들과 타이트하지만 꼼꼼한 교육과정으로 충분히 따라갈 수 있었습니다.",
//     registDate : "2020-10-11",
//     updateDate : null,
//     eduRate : 4.0,
//     lecRate : 5.0,
//     facRate : 2.5,
//     empRate : 3.5,
//     allRate : (4.0+5.0+2.5+3.5)/4,
//     like : 5,
//     hate : 1
// },
// {
//     rId : 2,
//     uId : "심재욱",
//     eId : 1,
//     title : "취업 걱정없는 교육과정",
//     content : "취업연계로 가는 기업들도 다 괜찮고 본인이 노력만 한다면 대기업 취업 기회도 매우 많이 주어진다.",
//     registDate : "2020-10-18",
//     updateDate : null,
//     eduRate : 3.5,
//     lecRate : 2.5,
//     facRate : 2.5,
//     empRate : 4.5,
//     allRate : (3.5+2.5+2.5+4.5)/4,
//     like : 6,
//     hate : 5
// },
// {
//     rId : 3,
//     uId : "테스트",
//     eId : 1,
//     title : "테스트입니다",
//     content : "테스트테스트테스트테스트",
//     registDate : "2020-10-21",
//     updateDate : "2020-10-23",
//     eduRate : 2.0,
//     lecRate : 1.0,
//     facRate : 1.5,
//     empRate : 4.5,
//     allRate : (2.0+1.0+1.5+4.5)/4,
//     like : 2,
//     hate : 9
// }]
[
    {    
        eId: 1,
        aId: 1,
        eTitle : "혁신성장 클라우드 마이크로 서비스 아키텍쳐",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        addrSimple : "서울 강남구",
        addrDetail : "서울특별시 구로구 구로중앙로34길 33-4 (구로동 영림빌딩)",
        telephone : "000-000-0000",
        aTitle : "멀티캠퍼스",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x90.png",
        rating : 4.5,
        review : [{
            rid : 1,
            uid : "서동주",
            eid : 1,
            title : "어렵지만 강사진과 내용 모두 훌륭한 교육",
            content : "비전공자였던 제 입장에서는 매우 생소하고 어려운 기술들이었지만 친절한 강사님들과 타이트하지만 꼼꼼한 교육과정으로 충분히 따라갈 수 있었습니다.",
            registDate : "2020-10-11",
            updateDate : null,
            eduRate : 4.0,
            lecRate : 5.0,
            facRate : 2.5,
            empRate : 3.5,
            allRate : (4.0+5.0+2.5+3.5)/4,
            like : 5,
            hate : 1
        },
        {
            rid : 2,
            uid : "심재욱",
            eid : 1,
            title : "취업 걱정없는 교육과정",
            content : "취업연계로 가는 기업들도 다 괜찮고 본인이 노력만 한다면 대기업 취업 기회도 매우 많이 주어진다.",
            registDate : "2020-10-18",
            updateDate : null,
            eduRate : 3.5,
            lecRate : 2.5,
            facRate : 2.5,
            empRate : 4.5,
            allRate : (3.5+2.5+2.5+4.5)/4,
            like : 6,
            hate : 5
        },
        {
            rid : 3,
            uid : "테스트",
            eid : 1,
            title : "테스트입니다",
            content : "테스트테스트테스트테스트",
            registDate : "2020-10-21",
            updateDate : "2020-10-23",
            eduRate : 2.0,
            lecRate : 1.0,
            facRate : 1.5,
            empRate : 4.5,
            allRate : (2.0+1.0+1.5+4.5)/4,
            like : 2,
            hate : 9
        }]
    },
    {    
        eId: 2,
        aId: 1,
        eTitle : "혁신성장 인공지능 보안 솔류션",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        addrSimple : "서울 강남구",
        addrDetail : "서울특별시 구로구 구로중앙로34길 33-4 (구로동 영림빌딩)",
        telephone : "000-000-0000",
        aTitle : "멀티캠퍼스",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x90.png",
        rating : 4.5,
        review : []
    },
    {    
        eId: 3,
        aId: 2,
        eTitle : "JAVA기반 빅데이터분석 개발자 양성",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        addrSimple : "인천 부평구",
        addrDetail : "서울특별시 구로구 구로중앙로34길 33-4 (구로동 영림빌딩)",
        telephone : "000-000-0000",
        aTitle : "그린컴퓨터아카데미",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x90.png",
        rating : 4.0,
        review : []
    },
    {    
        eId: 4,
        aId: 3,
        eTitle : "자바(JAVA) & 파이썬기반 빅데이터분석 머신러닝활용",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        addrSimple : "서울 서초구",
        addrDetail : "서울특별시 구로구 구로중앙로34길 33-4 (구로동 영림빌딩)",
        telephone : "000-000-0000",
        aTitle : "더조은컴퓨터학원",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x90.png",
        rating : 2.0,
        review : []
    },
    {    
        eId: 5,
        aId: 3,
        eTitle : "UI/UX 적응형반응형 웹디자인&웹퍼블리셔 A",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        addrSimple : "서울 서초구",
        addrDetail : "서울특별시 구로구 구로중앙로34길 33-4 (구로동 영림빌딩)",
        telephone : "000-000-0000",
        aTitle : "더조은컴퓨터학원",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x90.png",
        rating : 2.0,
        review : []
    },
    {    
        eId: 6,
        aId: 4,
        eTitle : "오픈API를 활용한 핀테크 개발자 양성과정",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        addrSimple : "대구 중구",
        addrDetail : "서울특별시 구로구 구로중앙로34길 33-4 (구로동 영림빌딩)",
        telephone : "000-000-0000",
        aTitle : "한국기술교육직업전문학교",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x90.png",
        rating : 3.0,
        review : []
    },
    {    
        eId: 7,
        aId: 5,
        eTitle : "SW(코딩) 교강사 양성과정",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        addrSimple : "부산 동래구",
        addrDetail : "서울특별시 구로구 구로중앙로34길 33-4 (구로동 영림빌딩)",
        telephone : "000-000-0000",
        aTitle : "비트캠프",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x90.png",
        rating : 4.5,
        review : []
    },
    {    
        eId: 8,
        aId: 6,
        eTitle : "스크래치로 배우는 COS 2급(코딩활용능력평가)",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        addrSimple : "경기 성남시 분당구",
        addrDetail : "서울특별시 구로구 구로중앙로34길 33-4 (구로동 영림빌딩)",
        telephone : "000-000-0000",
        aTitle : "이젠아이티아카데미",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x90.png",
        rating : 3.5,
        review : []
    },
    {    
        eId: 9,
        aId: 6,
        eTitle : "앱(App)의 새로운 바람, 타이젠(Tizen) 프로그래밍",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        addrSimple : "경기 성남시 분당구",
        addrDetail : "서울특별시 구로구 구로중앙로34길 33-4 (구로동 영림빌딩)",
        telephone : "000-000-0000",
        aTitle : "이젠아이티아카데미",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x90.png",
        rating : 3.5,
        review : []
    },
    {    
        eId: 10,
        aId: 6,
        eTitle : "스마트한 세상! IoT & 유비쿼터스 IT",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        addrSimple : "경기 성남시 분당구",
        addrDetail : "서울특별시 구로구 구로중앙로34길 33-4 (구로동 영림빌딩)",
        telephone : "000-000-0000",
        aTitle : "이젠아이티아카데미",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x90.png",
        rating : 3.5,
        review : []
    },
]

export default EduDetailTestData