const EduListTestData = [
    {    
        eId: 1,
        aId: 1,
        eTitle : "혁신성장 클라우드 마이크로 서비스 아키텍쳐",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        address : "서울 강남구",
        telephone : "000-000-0000",
        aTitle : "멀티캠퍼스",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x80.png",
        rating : ((4.0+5.0+2.5+3.5)/4+(3.5+2.5+2.5+4.5)/4+(2.0+1.0+1.5+4.5)/4)/3
    },
    {    
        eId: 2,
        aId: 1,
        eTitle : "혁신성장 인공지능 보안 솔류션",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        address : "서울 강남구",
        telephone : "000-000-0000",
        aTitle : "멀티캠퍼스",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x80.png",
        rating : 0
    },
    {    
        eId: 3,
        aId: 2,
        eTitle : "JAVA기반 빅데이터분석 개발자 양성",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        address : "인천 부평구",
        telephone : "000-000-0000",
        aTitle : "그린컴퓨터아카데미",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x80.png",
        rating : 0
    },
    {    
        eId: 4,
        aId: 3,
        eTitle : "자바(JAVA) & 파이썬기반 빅데이터분석 머신러닝활용",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        address : "서울 서초구",
        telephone : "000-000-0000",
        aTitle : "더조은컴퓨터학원",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x80.png",
        rating : 0
    },
    {    
        eId: 5,
        aId: 3,
        eTitle : "UI/UX 적응형반응형 웹디자인&웹퍼블리셔 A",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        address : "서울 서초구",
        telephone : "000-000-0000",
        aTitle : "더조은컴퓨터학원",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x80.png",
        rating : 0
    },
    {    
        eId: 6,
        aId: 4,
        eTitle : "오픈API를 활용한 핀테크 개발자 양성과정",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        address : "대구 중구",
        telephone : "000-000-0000",
        aTitle : "한국기술교육직업전문학교",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x80.png",
        rating : 0
    },
    {    
        eId: 7,
        aId: 5,
        eTitle : "SW(코딩) 교강사 양성과정",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        address : "부산 동래구",
        telephone : "000-000-0000",
        aTitle : "비트캠프",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x80.png",
        rating : 0
    },
    {    
        eId: 8,
        aId: 6,
        eTitle : "스크래치로 배우는 COS 2급(코딩활용능력평가)",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        address : "경기 성남시 분당구",
        telephone : "000-000-0000",
        aTitle : "이젠아이티아카데미",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x80.png",
        rating : 0
    },
    {    
        eId: 9,
        aId: 6,
        eTitle : "앱(App)의 새로운 바람, 타이젠(Tizen) 프로그래밍",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        address : "경기 성남시 분당구",
        telephone : "000-000-0000",
        aTitle : "이젠아이티아카데미",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x80.png",
        rating : 0
    },
    {    
        eId: 10,
        aId: 6,
        eTitle : "스마트한 세상! IoT & 유비쿼터스 IT",
        startDate : "2020-10-26",
        endDate : "2020-12-30",
        address : "경기 성남시 분당구",
        telephone : "000-000-0000",
        aTitle : "이젠아이티아카데미",
        homepage : "www.google.com",
        imgUrl : "https://via.placeholder.com/190x80.png",
        rating : 0
    },
]

export default EduListTestData