const report_test_data = [
    {
        id : 0,
        type: "영리목적/홍보성",
        date: "2020-10-22",
        detail: "학원홍보냄새가 지독합니다.",
        sender: "리자몽워터",
        post_type: "freeboard",
        post_id: 1,
        is_blind: false,
        is_done: false,
    },
    {
        id : 1,
        type: "영리목적/홍보성",
        date: "2020-10-22",
        detail: "학원홍보냄새가 지독합니다.",
        sender: "리자몽워터",
        post_type: "freeboard",
        post_id: 1,
        is_blind: false,
        is_done: true,
    },
    {
        id : 2,
        type: "욕설/인신공격",
        date: "2020-10-22",
        detail: "몰라서 물어봤는데 간단한 질문이라고 머리통 비었다는 폭언을 하였습니다. 세상에나 마상에나",
        sender: "리자몽워터",
        post_type: "question",
        post_id: 1285,
        is_blind: false,
        is_done: false,
    },
    {
        id : 3,
        type: "영리목적/홍보성",
        date: "2020-10-22",
        detail: "학원홍보냄새가 지독합니다.",
        sender: "리자몽워터",
        post_type: "freeboard",
        post_id: 1,
        is_blind: false,
        is_done: false,
    },
    {
        id : 4,
        type: "영리목적/홍보성",
        date: "2020-10-22",
        detail: "학원홍보냄새가 지독합니다.",
        sender: "리자몽워터",
        post_type: "freeboard",
        post_id: 1,
        is_blind: false,
        is_done: false,
    },
    {
        id : 5,
        type: "영리목적/홍보성",
        date: "2020-10-22",
        detail: "학원홍보냄새가 지독합니다.",
        sender: "리자몽워터",
        post_type: "freeboard",
        post_id: 1,
        is_blind: false,
        is_done: false,
    }
]

export default report_test_data