export default [
  {
    title: "test1 and Long name test title helloWorld",
    writer_id: "testUser1",
    writer_lv: "level 1",
    date: "2020.09.30",
    answer: 0,
    views: 22,
    tags: ["testTag1", "testTag2"],
    answerIcon: "../logo/logo_red_blank.png",
    userIcon: "../logo/logo_st.png",
    point: 200,
    addPoints: 1,
  },
  {
    title: "test2",
    writer_id: "testUser2",
    writer_lv: "level 2",
    date: "2020.09.29",
    answer: 3,
    views: 115,
    tags: ["testTag1", "testTag2", "testTag3"],
    answerIcon: "../logo/logo_yellow_blank.png",
    userIcon: "../logo/logo_st.png",
    point: 100,
    addPoints: 3,
  },
  {
    title: "test3",
    writer_id: "testUser3",
    writer_lv: "level 3",
    date: "2020.09.20",
    answer: 7,
    views: 241,
    tags: ["testTag5", "testTag9"],
    answerIcon: "../logo/logo_green_blank.png",
    userIcon: "../logo/logo_st.png",
    point: 150,
    addPoints: 7,
  },
  {
    title: "test4",
    writer_id: "testUser4",
    writer_lv: "level 4",
    date: "2020.09.19",
    answer: 2,
    views: 137,
    tags: ["testTag1", "testTag6"],
    answerIcon: "../logo/logo_yellow_blank.png",
    userIcon: "../logo/logo_st.png",
    point: 200,
    addPoints: 0,
  },
  {
    title: "test5",
    writer_id: "testUser5",
    writer_lv: "level 5",
    date: "2020.09.03",
    answer: 2,
    views: 87,
    tags: ["testTag6", "testTag7"],
    answerIcon: "../logo/logo_green_blank.png",
    userIcon: "../logo/logo_st.png",
    point: 1000,
    addPoints: 2,
  },
  {
    title: "test6",
    writer_id: "testUser6",
    writer_lv: "level 6",
    date: "2020.09.01",
    answer: 7,
    views: 255,
    tags: ["testTag3"],
    answerIcon: "../logo/logo_green_blank.png",
    userIcon: "../logo/logo_st.png",
    point: 350,
    addPoints: 3,
  },
]
